# Path to target SQLite database
db_path="/tmp/cache.db"

# ID to uniquely identify your nodes in your cluster
# It's recommended to always configure this
# node_id=1

# Path to persist the saved sequence map on disk for warm reboot
# If this file is missing Marmot has to download snapshot
# and replay all logs in order to restore database
# seq_map_path="/tmp/seq-map.cbor"


# Snapshots are used to limit log size and have a database snapshot backedup on your
# configured blob storage (NATS for now). This helps speedier recovery or cold boot
# nodes to come up. A Snapshot is taken every log entries are close to max_entries
# configured in replication_log section. It's recommended to use a large value
# for maximum entries in replication log, because SQLite can do 1000s of TPS
# replaying a couple thousands of entries should be really quick.
[snapshot]
# Disabling snapshot disables both restore and save
enabled=true
# Number of NATS replicas of snapshot object store (max 5)
replicas=1


# Change log that is published and persisted in JetStreams by Marmot.
# Marmot auto-configures missing JetStreams when booting up for you.
[replication_log]
# Number of replicas per log to configure
replicas=1
# Number of shards to divide the logs over, each JetStream and subject will be prefixed
# by the configured `subject_prefix` and `stream_prefix` under nats
shards=8
# Max log entries JetStream should persist, JetStream is configured to drop older entries
# Each JetStream is configured to persist on file.
max_entries=1024
# Enable log compression, uses zstd to compress logs as they are streamd to NATS
# This is useful for DB storing large blobs that can be compressed.
compress=true


# NATS server configurations
[nats]
# List of NATS server to use as boot server. Reference NATS documentation on how to pass
# authentication credentials as part of URL.
urls=[
    "nats://localhost:4222"
]
# Subject prefix used when publishing log entries, it's usually suffixed by shard number
# to get the full subject name
subject_prefix="marmot-change-log"
# JetStream name prefix used for publishing log entries, it's usually suffixed by shard number
# to get the full JetStream name
stream_prefix="marmot-changes"


# Console STDOUT configurations
[logging]
# Configure console logging
verbose=true
# "console" | "json"
format="console"